# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""The pull request an implementation is published under, and whose work it says
it carries.

The title is chosen from the branch's own first commit subject, falling back to
a prefix inferred from recent base history, so the PR reads like the repository
it lands in rather than like the orchestrator. The body pairs the `Resolves #N`
that closes the issue on merge with the dev session that wrote the branch, and
with the agent's closing message where the run produced one -- capped, and cut
on a boundary that leaves the Markdown around it intact.

The attribution line is what holds the two halves of this owner together. The
body states it, and the reuse below reads it back off a pull request of unknown
provenance: `find_open_pr` promises only that something is open on the branch,
so what it hands over may be this stage's own crashed attempt, an operator's,
or the `discussion` stage's plan PR sitting on the very ref the dev commits went
to. Its presence is the one thing that separates the first from the others,
which is why the same sentence is generated for both readings rather than
written twice.

Reuse rather than a second open is also what makes the publication re-runnable:
a tick that died between `open_pr` and the relabel comes back to a pull request
already carrying the commit and adopts it, instead of 422-ing on a duplicate.
"""
from __future__ import annotations

import logging
from pathlib import Path

from github.Issue import Issue

from orchestrator import config
from orchestrator.agents import AgentResult
from orchestrator.git.publication import (
    probes as _publication_probes,
    titles as _titles,
)
from orchestrator.github import client as _client, pinned_state as _pinned_state
from orchestrator.workflow.engine import comments as _comments
from orchestrator.workflow.stages.implementing import (
    models as _models,
    session_read as _session_read,
    state as _state,
)

log = logging.getLogger("orchestrator.workflow")


def _format_pr_agent_message(
    message: str, *, cap: int = _state._PR_BODY_AGENT_MESSAGE_CAP
) -> str:
    """Return the agent's final message ready to embed in a PR body.

    A message within `cap` is returned verbatim. A longer one is trimmed on the
    nearest paragraph -> line -> word boundary before `cap` and an explicit
    `_…(message truncated)_` marker is appended, so the PR body reads as
    intentionally clipped rather than severed mid-sentence. A dangling code
    fence in the trimmed region is closed first so the marker (and any following
    body) renders outside the half-open block instead of being swallowed by it.
    """
    if len(message) <= cap:
        return message
    head = message[:cap]
    # Prefer a paragraph break, then a line break, then a word boundary, so the
    # cut lands somewhere readable instead of mid-token.
    for sep in ("\n\n", "\n", " "):
        idx = head.rfind(sep)
        if idx > 0:
            head = head[:idx]
            break
    head = head.rstrip()
    # An odd count of ``` fences means the cut landed inside a fenced block;
    # close it so GitHub doesn't swallow the marker into the open code block.
    if head.count("```") % 2:
        head = f"{head}\n```"
    return f"{head}\n\n{_state._PR_BODY_TRUNCATION_MARKER}"


def _derive_pr_title(spec: config.RepoSpec, issue: Issue, wt: Path) -> str:
    """PR title for a freshly opened dev PR.

    Prefers the first commit's conventional subject; when that carries no
    recognizable `<type>:` prefix, one is inferred from recent base-branch
    history (`_infer_subject_prefix`) and applied to the issue title.
    """
    first_subject = _publication_probes._first_commit_subject(spec, wt)
    fallback_prefix = _titles._infer_subject_prefix(spec, wt, issue)
    return _titles._pr_title_from_commit_or_issue(
        issue, first_subject, fallback_prefix,
    )


def _dev_pr_attribution(state: _pinned_state.PinnedState) -> str:
    """Which dev session the branch on this PR was written by.

    Its own line because two owners need it: the body that states it, and the
    reuse below, which reads a PR of unknown provenance for it before adopting
    that PR as this implementation's.
    """
    _, dev_backend, _, dev_sid = _session_read._read_dev_session(state)
    session_id = dev_sid or "?"
    return f"Generated by orchestrator ({dev_backend} session `{session_id}`)."


def _build_pr_body(
    state: _pinned_state.PinnedState, issue: Issue, agent_result: AgentResult,
) -> str:
    """PR body: the `Resolves #N` line, the generating session's identity, and
    the (capped) final agent message when the run produced one."""
    body_parts = [
        f"Resolves #{issue.number}",
        "",
        _dev_pr_attribution(state),
    ]
    if agent_result.last_message.strip():
        body_parts += [
            "", "---", "_Last agent message:_", "",
            _format_pr_agent_message(agent_result.last_message),
        ]
    return "\n".join(body_parts)


def _reuse_or_open_pr(
    gh: _client.GitHubClient,
    spec: config.RepoSpec,
    issue: Issue,
    state: _pinned_state.PinnedState,
    work: _models._PRWork,
):
    """Return the PR for `branch`, reusing an open one or opening a new one.

    Recovers gracefully if a previous tick crashed between `open_pr` and the
    relabel: an existing open PR is reused instead of 422-ing on a duplicate.
    Opening a new PR posts the ":sparkles: PR opened" comment and emits the
    `pr_opened` event; reuse only logs.
    """
    pr = gh.find_open_pr(branch=work.branch, base=spec.base_branch)
    if pr is not None:
        log.info(
            "issue=#%s reusing existing PR #%d for %s",
            issue.number, pr.number, work.branch,
        )
        _attribute_reused_pr(gh, issue, state, work, pr)
        return pr
    pr = gh.open_pr(
        branch=work.branch, base=spec.base_branch,
        title=_derive_pr_title(spec, issue, work.worktree),
        body=_build_pr_body(state, issue, work.agent_result),
    )
    _comments._post_issue_comment(gh, issue, state, f":sparkles: PR opened: #{pr.number}")
    gh.emit_event(
        "pr_opened",
        issue_number=issue.number,
        stage=_state._IMPLEMENTING_STAGE,
        pr_number=pr.number,
        branch=work.branch,
        sha=getattr(pr.head, "sha", None) or None,
        retry_count=state.get(_state._RETRY_COUNT),
    )
    return pr


def _attribute_reused_pr(
    gh: _client.GitHubClient,
    issue: Issue,
    state: _pinned_state.PinnedState,
    work: _models._PRWork,
    pr,
) -> None:
    """Make a PR opened elsewhere describe the work now pushed onto it.

    What `find_open_pr` returns is only known to be open on this branch. The
    sharpest case is the `discussion` stage's plan PR: an issue relabeled here
    arrives with it open on the very branch the dev commits go to, so a silent
    reuse leaves a body saying the branch is one Markdown file and changes
    nothing else -- a claim the push just made false -- under the decomposer's
    session rather than the developer's, and with no `Resolves #N` to close
    the issue when it merges. An operator's own PR on the branch is the same
    problem with different words.

    The dev attribution is what decides. Its absence means the body is about
    something other than this implementation and is rewritten; its presence
    means this stage already wrote it (a tick that died between `open_pr` and
    the relabel), and everything it says -- including what a human added
    underneath -- is left alone.
    """
    if _dev_pr_attribution(state) in (getattr(pr, "body", "") or ""):
        return
    log.info(
        "issue=#%s rewriting reused PR #%d body to name this implementation",
        issue.number, pr.number,
    )
    gh.edit_pr_body(pr, _build_pr_body(state, issue, work.agent_result))
