# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""`read_only_relabel.py` screening a `discussion` park on the way in.

A read-only park is opaque to this stage's resume path, so an operator's
relabel has to be read as an unblock signal -- but only after the checkout is
looked at. A discussion agent that committed left work on the per-issue branch
that nobody reviewed, and the fresh-spawn path's recovered-worktree shortcut
would push it as a dev implementation and open a PR for it.

The guard serves both read-only stages, and the branch exercised here is the
one only a discussion can reach: it may open on a branch that already carries
a PR's commits, so ahead-of-base cannot be the question and the round anchor
is consulted instead. The question stage's half, whose contract forbids
finishing on a branch carrying anything, is covered from
`tests/workflow/stages/question/`. What the tick does once the guard has said
yes is `test_read_only_handoff.py`.
"""

from __future__ import annotations

import unittest

from tests.support.fakes import FakePR, FakePRRef
from tests.workflow.fixtures import (
    KEY_AWAITING_HUMAN,
    KEY_PARK_REASON,
    _PatchedWorkflowMixin,
    _agent,
    _issue_branch,
)

from tests.workflow.stages.implementing.read_only_relabel_test_support import (
    DEV_SESSION,
    HEAD_AFTER_COMMIT,
    HEAD_BEFORE_ROUND,
    KEY_ROUND_SHA,
    PARK_DISCUSSION_COMMITS,
    PARK_DISCUSSION_RESPONSE,
    PARK_DISCUSSION_UNSAFE_RELABEL,
)
from tests.workflow.stages.implementing.read_only_relabel_test_support import (
    KEY_PUBLISHING_SHA,
    KEY_READ_ONLY_BASELINE,
    KEY_ROUND_OPEN,
    PUSH_BRANCH,
    RUN_AGENT,
    UNEXPECTED_AGENT_MESSAGE,
    _ReadOnlyRelabelMixin,
    _seed_relabeled_discussion,
)

_UNSAFE_RELABEL_ISSUE_NUMBER = 990
_SAFE_RELABEL_ISSUE_NUMBER = 991
_INHERITED_RELABEL_ISSUE_NUMBER = 992
_MOVED_TIP_RELABEL_ISSUE_NUMBER = 993
_RESET_RELABEL_ISSUE_NUMBER = 994
_RESET_TO_BASE_ISSUE_NUMBER = 998
_VANISHED_REF_ISSUE_NUMBER = 999
_CRASHED_ROUND_ISSUE_NUMBER = 1030
_CRASHED_PUBLISH_ISSUE_NUMBER = 1031
_CLEAN_CRASH_ISSUE_NUMBER = 1032
_DETACHED_ROUND_ISSUE_NUMBER = 1033
_DETACHED_PUBLISH_ISSUE_NUMBER = 1034
_LOST_CHECKOUT_ISSUE_NUMBER = 1035
_UNREADABLE_TREE_ISSUE_NUMBER = 1036
# What a crash left where this host can still see it.
_ON_THE_BRANCH = "on-the-branch"
_DETACHED_CHECKOUT = "in-a-detached-checkout"
_NO_LOCAL_EVIDENCE = "nowhere-this-host-can-see"
# The same two crashes, with the commit made while the checkout was detached:
# before the publication marker, and after the PR it opened.
_DETACHED_CRASHES = (
    (_DETACHED_ROUND_ISSUE_NUMBER, {KEY_ROUND_OPEN: True}),
    (_DETACHED_PUBLISH_ISSUE_NUMBER, {KEY_PUBLISHING_SHA: HEAD_AFTER_COMMIT}),
)
_PUBLISHED_PR_NUMBER = 6100
# What the publication left on the PR it opened: the plan, under the
# decomposer's session, closing nothing when it merges.
_PLAN_PR_BODY = (
    "The plan, as agreed on the issue thread.\n\n"
    "Generated by orchestrator (claude session `d-sess-1`) in the "
    "`discussion` stage."
)
_BASE_TIP = "head-at-the-base-branch"
# The two ways the recorded ref stops matching its anchor: moved past it by a
# commit, and dragged back to base by an over-broad reset.
_UNCERTIFIED_TIPS = (
    (_MOVED_TIP_RELABEL_ISSUE_NUMBER, HEAD_AFTER_COMMIT),
    (_RESET_TO_BASE_ISSUE_NUMBER, _BASE_TIP),
)
# The two ways a branch ends a discussion ahead of base but unmoved by it:
# never written to, and written to then reset back to the anchor.
_CERTIFIED_TIP_PARKS = (
    (_INHERITED_RELABEL_ISSUE_NUMBER, PARK_DISCUSSION_RESPONSE),
    (_RESET_RELABEL_ISSUE_NUMBER, PARK_DISCUSSION_COMMITS),
)


def _published_plan_pr(issue_number: int) -> FakePR:
    """The plan PR a crashed publication opened and never recorded.

    Open on the per-issue branch, which is exactly where a dev push would land,
    so `find_open_pr` hands it straight to the reuse that rewrites its body to
    close the issue on merge.
    """
    return FakePR(
        number=_PUBLISHED_PR_NUMBER,
        head_branch=_issue_branch(issue_number),
        body=_PLAN_PR_BODY,
        head=FakePRRef(sha=HEAD_AFTER_COMMIT),
    )


class DiscussionRelabelToImplementingTest(
    unittest.TestCase, _PatchedWorkflowMixin, _ReadOnlyRelabelMixin,
):

    def test_a_committed_park_refuses_the_relabel(self) -> None:
        # The discussion agent committed and the stage parked on it, leaving
        # the anchor standing. The relabel must not become the route by which
        # that commit is pushed and a PR opened for it -- and the refusal has
        # to name the anchor as the reset target, because on a PR-backed issue
        # "reset to base" would throw the PR's commits away with the agent's.
        gh, issue = _seed_relabeled_discussion(
            _UNSAFE_RELABEL_ISSUE_NUMBER, PARK_DISCUSSION_COMMITS,
        )

        mocks = self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=_issue_branch(issue.number),
            run_agent=_agent(last_message=UNEXPECTED_AGENT_MESSAGE),
            has_new_commits=True,
            branch_tip_sha=HEAD_AFTER_COMMIT,
        )

        mocks[RUN_AGENT].assert_not_called()
        mocks[PUSH_BRANCH].assert_not_called()
        self.assertEqual(gh.opened_prs, [])
        pinned_data = gh.pinned_data(issue.number)
        self.assertTrue(pinned_data[KEY_AWAITING_HUMAN])
        self.assertEqual(
            pinned_data[KEY_PARK_REASON], PARK_DISCUSSION_UNSAFE_RELABEL,
        )
        refusal = gh.posted_comments[-1][1]
        # What the refusal says is the contract it is enforcing: the stage
        # publishes the plan its humans confirmed, itself, and ships nothing
        # else as dev work -- not that its agent may never write.
        self.assertIn(
            "Nothing the discussion stage leaves in the worktree is shipped "
            "as a dev implementation",
            refusal,
        )
        self.assertIn("publishes the one plan it confirmed", refusal)
        self.assertIn(HEAD_BEFORE_ROUND, refusal)
        self.assertNotIn("branch -D", refusal)

    def test_a_branch_still_on_the_anchor_relabels(self) -> None:
        # A branch ahead of base that this stage did not move, from both
        # directions. `discussion_response` is the issue that reached the
        # stage from a PR and was only ever read; `discussion_commits` is the
        # same issue after the agent committed and an operator reset back to
        # the anchor, which drops that commit and keeps the PR's underneath.
        # Asking "is this branch ahead of base" would refuse both over the
        # dev's own earlier work, and the second would have no way out that
        # did not also destroy the PR.
        for issue_number, park_reason in _CERTIFIED_TIP_PARKS:
            with self.subTest(park_reason=park_reason):
                self._assert_relabel_allowed(issue_number, park_reason)

    def test_a_tip_off_the_anchor_refuses_the_relabel(self) -> None:
        # The recorded ref is compared to the recorded SHA whatever it now
        # stands in relation to base, because ahead-of-base answers neither
        # end of this. A tip past the anchor is the agent's commit. A tip
        # reset all the way TO base is not ahead of base at all, so the cheap
        # question calls it clean -- while on the PR-backed issue this park
        # exists for, that reset threw away the commits the round was
        # certified against and the violation went unresolved.
        for issue_number, tip in _UNCERTIFIED_TIPS:
            with self.subTest(tip=tip):
                self._assert_relabel_refused(issue_number, tip)

    def test_an_unreadable_tree_refuses_the_relabel(self) -> None:
        # `git status` could not report on the checkout -- a corrupt index, a
        # half-removed directory. The list form of that read answers with no
        # paths, which is what a clean tree answers, and accepting on it clears
        # the discussion stage's records and lets worktree creation force-remove
        # a tree nobody has proved is empty: the evidence an operator was parked
        # to look at, gone before they read it.
        gh = self._assert_relabel_refused(
            _UNREADABLE_TREE_ISSUE_NUMBER, HEAD_BEFORE_ROUND, readable=False,
        )

        self.assertIn("could not be read", gh.posted_comments[-1][1])

    def test_a_vanished_ref_is_not_a_violation(self) -> None:
        # No local branch means nothing local to attribute: this stage never
        # pushes, so a PR-backed checkout is rebuilt from the PR head, which
        # never carried its work. Convicting here would strand the pruned
        # -worktree recovery an operator has no way to undo.
        gh, issue = _seed_relabeled_discussion(
            _VANISHED_REF_ISSUE_NUMBER, PARK_DISCUSSION_RESPONSE,
        )

        mocks = self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=None,
            run_agent=_agent(session_id=DEV_SESSION, last_message="implemented"),
            has_new_commits=[False, True],
            branch_tip_sha="",
            head_shas=(HEAD_BEFORE_ROUND, HEAD_BEFORE_ROUND, HEAD_AFTER_COMMIT),
        )

        mocks[RUN_AGENT].assert_called_once()
        self.assertNotEqual(
            gh.pinned_data(issue.number).get(KEY_PARK_REASON),
            PARK_DISCUSSION_UNSAFE_RELABEL,
        )

    def test_a_clean_park_lets_the_dev_run(self) -> None:
        # The ordinary exit: the humans settled the design, the tree is clean,
        # and the relabel IS the unblock signal. The park is dropped and the
        # dev spawns fresh rather than resuming a discussion nobody is having.
        gh, issue = _seed_relabeled_discussion(
            _SAFE_RELABEL_ISSUE_NUMBER, PARK_DISCUSSION_RESPONSE,
        )

        mocks = self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=None,
            run_agent=_agent(session_id=DEV_SESSION, last_message="implemented"),
            has_new_commits=[False, True],
            head_shas=(HEAD_BEFORE_ROUND, HEAD_BEFORE_ROUND, HEAD_AFTER_COMMIT),
        )

        spawned = mocks[RUN_AGENT]
        spawned.assert_called_once()
        self.assertIn("You are the implementer", spawned.call_args.args[1])
        self.assertEqual(len(gh.opened_prs), 1)
        pinned_data = gh.pinned_data(issue.number)
        self.assertFalse(pinned_data.get(KEY_AWAITING_HUMAN))
        self.assertIsNone(pinned_data.get(KEY_PARK_REASON))

    def _assert_relabel_refused(
        self, issue_number: int, tip: str, *, readable: bool = True,
    ):
        """One refused relabel, and the client that recorded the refusal.

        `readable` is the other way a checkout earns one: not a tip the guard
        can convict, but a `git status` that never answered at all.
        """
        gh, issue = _seed_relabeled_discussion(
            issue_number, PARK_DISCUSSION_RESPONSE,
        )

        mocks = self._run_implementing_on_worktree(
            gh,
            issue,
            # None is the shape a reset-to-base branch reports: nothing is
            # ahead of base any more, so the guard has only the anchor left.
            unpushed_branch=(
                _issue_branch(issue.number) if tip == HEAD_AFTER_COMMIT else None
            ),
            run_agent=_agent(last_message=UNEXPECTED_AGENT_MESSAGE),
            has_new_commits=tip == HEAD_AFTER_COMMIT,
            branch_tip_sha=tip,
            head_shas=(HEAD_BEFORE_ROUND,),
            tree_readable=readable,
        )

        mocks[RUN_AGENT].assert_not_called()
        mocks[PUSH_BRANCH].assert_not_called()
        self.assertEqual(gh.opened_prs, [])
        pinned_data = gh.pinned_data(issue.number)
        self.assertEqual(
            pinned_data[KEY_PARK_REASON], PARK_DISCUSSION_UNSAFE_RELABEL,
        )
        # The anchor stands, so the next tick still has something to measure by.
        self.assertEqual(pinned_data[KEY_ROUND_SHA], HEAD_BEFORE_ROUND)
        return gh

class CrashedDiscussionRelabelTest(
    unittest.TestCase, _PatchedWorkflowMixin, _ReadOnlyRelabelMixin,
):
    """A relabel onto a discussion tick that never reached a disposition.

    Both in-flight records are written BEFORE the thing they describe and
    retired by the disposition that reports it, and neither depends on
    `awaiting_human` -- an opening round leaves the issue unparked by design.
    So a tick that died after the agent committed, or after its plan PR was
    opened, leaves no park at all and a branch carrying the plan. Read as an
    ordinary relabel, the fresh-spawn path's recovered-worktree shortcut pushes
    that plan as a dev implementation: one push, the plan PR reused and its body
    rewritten to close the issue, and the label moved to validating with no
    developer having run.
    """

    def test_an_unreported_round_refuses_the_relabel(self) -> None:
        _gh, refusal = self._relabel_over_crash(
            _CRASHED_ROUND_ISSUE_NUMBER, **{KEY_ROUND_OPEN: True},
        )

        self.assertIn("a discussion-stage round that never reported", refusal)
        # The anchor is the reset target, as it is for every commit refusal.
        self.assertIn(HEAD_BEFORE_ROUND, refusal)

    def test_an_unfinished_publication_refuses(self) -> None:
        _gh, refusal = self._relabel_over_crash(
            _CRASHED_PUBLISH_ISSUE_NUMBER,
            **{KEY_PUBLISHING_SHA: HEAD_AFTER_COMMIT},
        )

        self.assertIn(
            "a discussion-stage publication that never finished", refusal,
        )
        # And the way out leads with the label that finishes it: the commit may
        # already be pushed with a pull request open against it, so telling an
        # operator to reset first would ask them to destroy it.
        self.assertIn("Relabel back to `discussion`", refusal)

    def test_a_crash_before_the_commit_hands_over(self) -> None:
        # The same records, on a branch the round never moved. Nothing was
        # written that this stage may not ship, so the relabel IS the unblock
        # signal -- and the stale records go with the park, or the discussion
        # stage would later claim the commit the dev is about to make.
        gh, issue = _seed_relabeled_discussion(
            _CLEAN_CRASH_ISSUE_NUMBER, None, **{KEY_ROUND_OPEN: True},
        )

        # Interrupted, so the handoff's own write is the only durable one and
        # what it recorded is what the assertions read.
        mocks = self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=_issue_branch(issue.number),
            run_agent=_agent(interrupted=True),
            has_new_commits=True,
            branch_tip_sha=HEAD_BEFORE_ROUND,
            head_shas=(HEAD_BEFORE_ROUND, HEAD_BEFORE_ROUND, HEAD_AFTER_COMMIT),
        )

        spawned = mocks[RUN_AGENT]
        spawned.assert_called_once()
        pinned_data = gh.pinned_data(issue.number)
        self.assertIsNone(pinned_data[KEY_ROUND_OPEN])
        self.assertEqual(
            pinned_data[KEY_READ_ONLY_BASELINE], HEAD_BEFORE_ROUND,
        )

    def test_a_detached_commit_refuses_the_relabel(self) -> None:
        # The same two crashes with the commit made off the branch: every named
        # ref is exactly where the round opened it -- nothing is ahead of base,
        # the recorded branch still sits on the anchor -- and the plan is in the
        # tree the developer would be handed. The creators keep that checkout as
        # it stands and the shortcut pushes whatever HEAD is, so the tip this
        # guard has to prove is the checkout's own.
        for issue_number, record in _DETACHED_CRASHES:
            with self.subTest(record=record):
                _gh, refusal = self._relabel_over_crash(
                    issue_number, evidence=_DETACHED_CHECKOUT, **record,
                )

                self.assertIn(HEAD_AFTER_COMMIT, refusal)

    def test_a_lost_checkout_holds_the_publication(self) -> None:
        # The reproduction a fresh host gives: the plan was pushed and its PR
        # opened, the tick died before recording either, and this host has
        # neither the checkout nor the local ref. Every local probe reads clean
        # -- nothing on disk, nothing ahead of base, no tip to compare -- so the
        # marker is the only thing left that knows a publication is out there.
        # Handed over on that reading, the dev builds from base and its push
        # takes a lease read live off the remote: the published plan is
        # overwritten, its PR adopted, and its body rewritten to close the
        # issue on merge.
        gh, refusal = self._relabel_over_crash(
            _LOST_CHECKOUT_ISSUE_NUMBER,
            evidence=_NO_LOCAL_EVIDENCE,
            pull_request=_published_plan_pr(_LOST_CHECKOUT_ISSUE_NUMBER),
            **{KEY_PUBLISHING_SHA: HEAD_AFTER_COMMIT},
        )

        self.assertIn(HEAD_AFTER_COMMIT, refusal)
        # The marker survives, because the stage that owns it is the one that
        # can finish it -- and the refusal says so.
        self.assertEqual(
            gh.pinned_data(_LOST_CHECKOUT_ISSUE_NUMBER)[KEY_PUBLISHING_SHA],
            HEAD_AFTER_COMMIT,
        )
        self.assertIn("Relabel back to `discussion`", refusal)
        # The plan PR is still the decomposer's, saying what it said.
        self.assertEqual(gh.get_pr(_PUBLISHED_PR_NUMBER).body, _PLAN_PR_BODY)

    def _relabel_over_crash(
        self,
        issue_number: int,
        *,
        evidence: str = _ON_THE_BRANCH,
        pull_request=None,
        **records,
    ):
        """Relabel an issue whose crashed round left its work behind.

        `evidence` is what this host can still see of it: the commit on the
        branch, the commit in a checkout whose refs never moved, or -- on a
        fresh clone -- nothing at all. `pull_request` is what GitHub holds
        beside that, which no local probe can see: the plan PR a crashed
        publication opened and never recorded. It is put where `find_open_pr`
        looks, so a handover would really reach the reuse that rewrites its
        body to close the issue.
        """
        gh, issue = _seed_relabeled_discussion(issue_number, None, **records)
        if pull_request is not None:
            gh.add_pr(pull_request)
            if not pull_request.merged:
                gh.existing_open_pr[pull_request.head_branch] = pull_request

        mocks = self._run_crashed_relabel(gh, issue, evidence)

        spawned = mocks[RUN_AGENT]
        spawned.assert_not_called()
        mocks[PUSH_BRANCH].assert_not_called()
        self.assertEqual(gh.opened_prs, [])
        self.assertEqual(gh.edited_pr_bodies, [])
        # Nothing moved the issue on, least of all to validating.
        self.assertEqual(gh.label_history, [])
        pinned_data = gh.pinned_data(issue.number)
        self.assertTrue(pinned_data[KEY_AWAITING_HUMAN])
        self.assertEqual(
            pinned_data[KEY_PARK_REASON], PARK_DISCUSSION_UNSAFE_RELABEL,
        )
        return gh, gh.posted_comments[-1][1]

    def _run_crashed_relabel(self, gh, issue, evidence: str):
        """One relabel tick over whatever local evidence the crash left."""
        refused = _agent(last_message=UNEXPECTED_AGENT_MESSAGE)
        if evidence == _NO_LOCAL_EVIDENCE:
            return self._run_implementing_without_checkout(
                gh, issue, run_agent=refused, has_new_commits=True,
                branch_tip_sha="",
            )
        detached = evidence == _DETACHED_CHECKOUT
        return self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=None if detached else _issue_branch(issue.number),
            run_agent=refused,
            has_new_commits=True,
            branch_tip_sha=HEAD_BEFORE_ROUND if detached else HEAD_AFTER_COMMIT,
            head_shas=(HEAD_AFTER_COMMIT,),
        )


if __name__ == "__main__":
    unittest.main()
