# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""The PR this stage finds already open on the branch it just pushed.

`find_open_pr` promises one thing: something is open on this ref. What it is
can be a PR this stage opened and crashed before recording, one an operator
opened by hand, or -- the case that arrives by design -- the `discussion`
stage's plan PR, which is open on the very branch the dev commits go to. The
first may be adopted as it stands; the others are describing something the push
has just made untrue, and adopting one silently leaves a PR that claims the
branch is a design document, names the decomposer's session, and closes no
issue when it merges.
"""

from __future__ import annotations

import unittest

from orchestrator import config
from tests.support.fakes import FakePR, FakePRRef
from tests.workflow.fixtures import (
    _agent,
    _issue_branch,
    _PatchedWorkflowMixin,
)
from tests.workflow.stages.implementing.read_only_relabel_test_support import (
    DEV_SESSION,
    HEAD_AFTER_COMMIT,
    KEY_PLAN_PATH,
    KEY_PLAN_SHA,
    KEY_PR_NUMBER,
    KEY_ROUND_SHA,
    PARK_DISCUSSION_PLAN_PUBLISHED,
    _ReadOnlyRelabelMixin,
    _seed_relabeled_discussion,
)

_REUSED_PLAN_ISSUE_NUMBER = 1004
_RECOVERED_PR_ISSUE_NUMBER = 1005
_HANDOFF_PR_NUMBER = 5150

_PLAN_PATH = f"plans/issue-{_REUSED_PLAN_ISSUE_NUMBER}.md"
_PLAN_COMMIT = "the-commit-the-plan-pr-carried"
_IMPLEMENTED = "implemented"
KEY_BRANCH = "branch"

# What the discussion stage left on the PR it opened: true of the branch it
# published, false of the branch the moment a dev commit lands on it.
_PLAN_CLAIM = "this branch changes nothing else"
_PLAN_BODY = (
    f"Plan for #{_REUSED_PLAN_ISSUE_NUMBER}, as agreed on the issue thread.\n\n"
    "Generated by orchestrator (claude session `d-sess-1`) in the "
    f"`discussion` stage.\n\nThe plan is in `{_PLAN_PATH}`; {_PLAN_CLAIM}."
)


class PlanPrReuseTest(
    unittest.TestCase, _PatchedWorkflowMixin, _ReadOnlyRelabelMixin,
):
    """What a PR already open on the branch is made to say once we push."""

    def test_a_reused_plan_pr_body_is_rewritten(self) -> None:
        # The plan PR is open on the very branch the dev commits go to, so the
        # push turns its body into a false statement: it says the branch is
        # one Markdown file and nothing else, names the decomposer's session
        # rather than the developer's, and closes nothing when it merges.
        gh, issue = self._seed_open_plan_pr(_REUSED_PLAN_ISSUE_NUMBER)

        self._run_publishing_tick(gh, issue)

        self.assertEqual(gh.opened_prs, [])
        self.assertEqual(
            [number for number, _ in gh.edited_pr_bodies], [_HANDOFF_PR_NUMBER],
        )
        _, rewritten = gh.edited_pr_bodies[0]
        self.assertIn(f"Resolves #{issue.number}", rewritten)
        self.assertIn(self._dev_attribution(), rewritten)
        self.assertNotIn(_PLAN_CLAIM, rewritten)

    def test_a_body_naming_this_dev_stands(self) -> None:
        # The ordinary reuse: our own PR, recovered by a later tick after one
        # died between opening it and the relabel. Rewriting it would throw
        # away whatever a human added underneath.
        annotated = f"{self._dev_attribution()}\n\nand a reviewer's note"
        gh, issue = self._seed_open_plan_pr(
            _RECOVERED_PR_ISSUE_NUMBER, body=annotated,
        )

        self._run_publishing_tick(gh, issue)

        self.assertEqual(gh.edited_pr_bodies, [])
        self.assertEqual(gh.get_pr(_HANDOFF_PR_NUMBER).body, annotated)

    def _dev_attribution(self) -> str:
        """The line that says this implementation's session wrote the branch."""
        return f"Generated by orchestrator ({config.DEV_AGENT} session `{DEV_SESSION}`)."

    def _seed_open_plan_pr(self, issue_number: int, *, body: str = _PLAN_BODY):
        """An issue relabeled here with its plan PR still open on the branch."""
        gh, issue = _seed_relabeled_discussion(
            issue_number,
            PARK_DISCUSSION_PLAN_PUBLISHED,
            **{
                KEY_PLAN_PATH: _PLAN_PATH,
                KEY_PR_NUMBER: _HANDOFF_PR_NUMBER,
                KEY_PLAN_SHA: _PLAN_COMMIT,
                # The anchor publication left: it moves onto the commit it put
                # on the PR, so the branch, the record, and that PR's head all
                # name the same tip until a human moves one of them.
                KEY_ROUND_SHA: _PLAN_COMMIT,
                # Written beside `pr_number` by the publication that opened
                # it, and what keeps the branch resolution off the legacy name.
                KEY_BRANCH: _issue_branch(issue_number),
            },
        )
        branch = _issue_branch(issue_number)
        plan_pr = FakePR(
            number=_HANDOFF_PR_NUMBER,
            head_branch=branch,
            body=body,
            head=FakePRRef(sha=_PLAN_COMMIT),
        )
        gh.add_pr(plan_pr)
        gh.existing_open_pr[branch] = plan_pr
        return gh, issue

    def _run_publishing_tick(self, gh, issue):
        """One implementing tick that commits and pushes onto that branch."""
        return self._run_implementing_on_worktree(
            gh,
            issue,
            unpushed_branch=_issue_branch(issue.number),
            run_agent=_agent(session_id=DEV_SESSION, last_message=_IMPLEMENTED),
            has_new_commits=True,
            branch_tip_sha=_PLAN_COMMIT,
            head_shas=(_PLAN_COMMIT, _PLAN_COMMIT, HEAD_AFTER_COMMIT),
        )

if __name__ == "__main__":
    unittest.main()
